### ISSUE TITLE
Cannot ping 1.8 / 1.8.8 server

### ISSUE THREAD

**Issue by fabien91** [zh32/TeleportSigns#14]
Hi,

I've try to updated last version of TeleportSigns, it work with server in 1.9 but teleportsign cannot ping on 1.8.8 server.
Can you resolve this please ?

Sincerely,
Fabien

**Comment by zh32** [comment]
Hi,

I have added support for minecraft 1.7/1.8 servers in [14-minecraft1.8-bc](https://github.com/zh32/TeleportSigns/tree/14-minecraft1.8-bc) Give it a try.

Thanks for the report!

**Comment by fabien91** [comment]
It's work but i've an other problem after i've try to restart my server and i've an error "Too many open files".

It's first time i've seen this error just after the installation of your plugin.

**Comment by zh32** [comment]
This shouldn't be related to this plugin/changes I made. If the error persists please submit a new issue with enough information to reproduce the error. Thanks!

The solution to this issue will be present in version 2.1.
