### ISSUE TITLE
Exception after /tsreload and /stop

### ISSUE THREAD

**Issue by fabien91** [zh32/TeleportSigns#22]
Hi,

Your plugin works but when i've place signs and i've write in minecraft chat /tsreload and after /stop
I've this error in loop : http://pastebin.com/ATjfrWJy

Sincerely,
Fabien

**Comment by zh32** [comment]
This should be fixed now and the solution comes with the next upcoming release.
https://github.com/zh32/TeleportSigns/releases/download/2.0-RC2/TeleportSigns.jar

**Comment by fabien91** [comment]
Not resolve look this please (i've compliled the last version of course)

![notresolved](https://cloud.githubusercontent.com/assets/5675697/14588244/7d67e714-04c4-11e6-98c9-cb60945c0d0e.jpg)
![javavisualvm](https://cloud.githubusercontent.com/assets/5675697/14588245/7ebdcc82-04c4-11e6-81f5-4833ad891e22.jpg)

When someone write /tsreload many task are created and cause crash (and can crash bungeecord ?)

http://pastebin.com/jaSQFe0n
